// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v4.25.1
// source: src/internal/proto/grpc.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TaskStatus int32

const (
	TaskStatus_NEWTASKOK         TaskStatus = 0
	TaskStatus_IMPLANTRESPONSEOK TaskStatus = 1
	TaskStatus_IMPLANTLOST       TaskStatus = 2
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "NEWTASKOK",
		1: "IMPLANTRESPONSEOK",
		2: "IMPLANTLOST",
	}
	TaskStatus_value = map[string]int32{
		"NEWTASKOK":         0,
		"IMPLANTRESPONSEOK": 1,
		"IMPLANTLOST":       2,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_src_internal_proto_grpc_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_src_internal_proto_grpc_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_src_internal_proto_grpc_proto_rawDescGZIP(), []int{0}
}

type TaskId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
}

func (x *TaskId) Reset() {
	*x = TaskId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_internal_proto_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskId) ProtoMessage() {}

func (x *TaskId) ProtoReflect() protoreflect.Message {
	mi := &file_src_internal_proto_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskId.ProtoReflect.Descriptor instead.
func (*TaskId) Descriptor() ([]byte, []int) {
	return file_src_internal_proto_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *TaskId) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type AliveMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImplantID string `protobuf:"bytes,1,opt,name=ImplantID,proto3" json:"ImplantID,omitempty"`
	IpAddr    string `protobuf:"bytes,2,opt,name=IpAddr,proto3" json:"IpAddr,omitempty"`
	OS        string `protobuf:"bytes,3,opt,name=OS,proto3" json:"OS,omitempty"`
}

func (x *AliveMsg) Reset() {
	*x = AliveMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_internal_proto_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AliveMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveMsg) ProtoMessage() {}

func (x *AliveMsg) ProtoReflect() protoreflect.Message {
	mi := &file_src_internal_proto_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveMsg.ProtoReflect.Descriptor instead.
func (*AliveMsg) Descriptor() ([]byte, []int) {
	return file_src_internal_proto_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *AliveMsg) GetImplantID() string {
	if x != nil {
		return x.ImplantID
	}
	return ""
}

func (x *AliveMsg) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *AliveMsg) GetOS() string {
	if x != nil {
		return x.OS
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID    string     `protobuf:"bytes,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	ImplantID string     `protobuf:"bytes,2,opt,name=ImplantID,proto3" json:"ImplantID,omitempty"`
	Command   string     `protobuf:"bytes,3,opt,name=Command,proto3" json:"Command,omitempty"`
	Status    TaskStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=TaskStatus" json:"Status,omitempty"`
	Result    string     `protobuf:"bytes,5,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_internal_proto_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_src_internal_proto_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_src_internal_proto_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *Task) GetImplantID() string {
	if x != nil {
		return x.ImplantID
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_NEWTASKOK
}

func (x *Task) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type NewTaskResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status TaskStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=TaskStatus" json:"Status,omitempty"`
}

func (x *NewTaskResult) Reset() {
	*x = NewTaskResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_internal_proto_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTaskResult) ProtoMessage() {}

func (x *NewTaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_src_internal_proto_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTaskResult.ProtoReflect.Descriptor instead.
func (*NewTaskResult) Descriptor() ([]byte, []int) {
	return file_src_internal_proto_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *NewTaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_NEWTASKOK
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_internal_proto_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_src_internal_proto_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_src_internal_proto_grpc_proto_rawDescGZIP(), []int{4}
}

var File_src_internal_proto_grpc_proto protoreflect.FileDescriptor

var file_src_internal_proto_grpc_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x20, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x22, 0x50, 0x0a, 0x08, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a,
	0x09, 0x49, 0x6d, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x49, 0x6d, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x49,
	0x70, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x4f, 0x53, 0x22, 0x93, 0x01, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6d, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6d, 0x70, 0x6c, 0x61, 0x6e, 0x74,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x23, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x34, 0x0a, 0x0d, 0x4e, 0x65, 0x77,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x43, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x45, 0x57, 0x54, 0x41, 0x53,
	0x4b, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x4d, 0x50, 0x4c, 0x41, 0x4e, 0x54,
	0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x49, 0x4d, 0x50, 0x4c, 0x41, 0x4e, 0x54, 0x4c, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x32, 0xb7, 0x01,
	0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x1a,
	0x0e, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x1e, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x07, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x1a, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x1f, 0x0a, 0x0e, 0x49, 0x6d, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x22, 0x0a, 0x11, 0x49, 0x6d, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x06, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x49, 0x6d, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x41,
	0x6c, 0x69, 0x76, 0x65, 0x12, 0x09, 0x2e, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x4d, 0x73, 0x67, 0x1a,
	0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x6e, 0x69, 0x72, 0x65, 0x69, 0x74, 0x64, 0x65, 0x76, 0x2f,
	0x67, 0x6f, 0x2d, 0x43, 0x32, 0x2d, 0x50, 0x72, 0x61, 0x6e, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_internal_proto_grpc_proto_rawDescOnce sync.Once
	file_src_internal_proto_grpc_proto_rawDescData = file_src_internal_proto_grpc_proto_rawDesc
)

func file_src_internal_proto_grpc_proto_rawDescGZIP() []byte {
	file_src_internal_proto_grpc_proto_rawDescOnce.Do(func() {
		file_src_internal_proto_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_internal_proto_grpc_proto_rawDescData)
	})
	return file_src_internal_proto_grpc_proto_rawDescData
}

var file_src_internal_proto_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_internal_proto_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_internal_proto_grpc_proto_goTypes = []interface{}{
	(TaskStatus)(0),       // 0: TaskStatus
	(*TaskId)(nil),        // 1: TaskId
	(*AliveMsg)(nil),      // 2: AliveMsg
	(*Task)(nil),          // 3: Task
	(*NewTaskResult)(nil), // 4: NewTaskResult
	(*Empty)(nil),         // 5: Empty
}
var file_src_internal_proto_grpc_proto_depIdxs = []int32{
	0, // 0: Task.Status:type_name -> TaskStatus
	0, // 1: NewTaskResult.Status:type_name -> TaskStatus
	3, // 2: Server.AdminNewTask:input_type -> Task
	1, // 3: Server.AdminGetTask:input_type -> TaskId
	5, // 4: Server.ImplantGetTask:input_type -> Empty
	3, // 5: Server.ImplantResultTask:input_type -> Task
	2, // 6: Server.ImplantAlive:input_type -> AliveMsg
	4, // 7: Server.AdminNewTask:output_type -> NewTaskResult
	3, // 8: Server.AdminGetTask:output_type -> Task
	3, // 9: Server.ImplantGetTask:output_type -> Task
	5, // 10: Server.ImplantResultTask:output_type -> Empty
	5, // 11: Server.ImplantAlive:output_type -> Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_internal_proto_grpc_proto_init() }
func file_src_internal_proto_grpc_proto_init() {
	if File_src_internal_proto_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_internal_proto_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_internal_proto_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AliveMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_internal_proto_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_internal_proto_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTaskResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_internal_proto_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_internal_proto_grpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_internal_proto_grpc_proto_goTypes,
		DependencyIndexes: file_src_internal_proto_grpc_proto_depIdxs,
		EnumInfos:         file_src_internal_proto_grpc_proto_enumTypes,
		MessageInfos:      file_src_internal_proto_grpc_proto_msgTypes,
	}.Build()
	File_src_internal_proto_grpc_proto = out.File
	file_src_internal_proto_grpc_proto_rawDesc = nil
	file_src_internal_proto_grpc_proto_goTypes = nil
	file_src_internal_proto_grpc_proto_depIdxs = nil
}
